apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: argocd-image-updater
data:
  registries.conf: |
    registries:
      - name: Docker Hub
        api_url: https://registry-1.docker.io
        prefix: docker.io
        credentials: ext:/auth/dockerhub
      - name: GitHub Container Registry
        api_url: https://ghcr.io
        prefix: ghcr.io
        credentials: ext:/auth/ghcr
  registries.conf.d: |
    registries:
      - name: Docker Hub
        api_url: https://registry-1.docker.io
        prefix: docker.io
        credentials: ext:/auth/dockerhub
      - name: GitHub Container Registry
        api_url: https://ghcr.io
        prefix: ghcr.io
        credentials: ext:/auth/ghcr
  argocd-image-updater-config: |
    log.level: info
    registries:
      - name: Docker Hub
        api_url: https://registry-1.docker.io
        prefix: docker.io
        credentials: ext:/auth/dockerhub
      - name: GitHub Container Registry
        api_url: https://ghcr.io
        prefix: ghcr.io
        credentials: ext:/auth/ghcr
    applications:
      - name: my-app
        namespace: prometheus
        images:
          - image: my-app
            updateStrategy: semver
            semverConstraint: ">=0.1.0"
            matchTags: ".*"
            allowTags: ".*"
            pullSecrets:
              - name: dockerhub-secret 