apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- rollout.yaml
- ingress.yaml
- servicemonitor.yaml
- grafana-dashboard.yaml
images:
- name: docker.io/rorychan0697/my-app
  newTag: v0.12.0
