apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- servicemonitor.yaml
- grafana-dashboard.yaml

images:
- name: docker.io/rorychan0697/my-app
  newName: docker.io/rorychan0697/my-app
  newTag: 0.1.0
