apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andrejryzikov/k8s-prometheus-test.git  # Замените на URL вашего репозитория
    targetRevision: HEAD
    path: gitops-repo/apps/my-app/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 