apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: my-app
    app.kubernetes.io/instance: my-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=docker.io/rorychan0697/my-app:*
    argocd-image-updater.argoproj.io/app.update-strategy: semver
    argocd-image-updater.argoproj.io/app.write-back-method: git:kustomization
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: git@github.com:aryzhykau/argocd-prometheus-test.git
    targetRevision: HEAD
    path: apps/my-app/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true 